[package]
name = "raycast"
version = "0.1.0"
edition = "2024"

[dependencies]
colorgrad = "0.7.1"
dyn-clone = "1.0.19"
image = "0.25.6"
indicatif = "0.17.11"
noise = "0.9.0"
rand = "0.9.1"
rand_chacha = "0.9.0"
rayon = "1.10.0"
